export type SegmentType = "user"|"host"|"userHost"|"directory"|"gitBranch"|"gitStatus"|"exitCode"|"duration"|"time"|"venv"|"node"|"literal"|"newline";
export interface SegmentDefinition { id: SegmentType; label: string; sample: string; }
export const SEGMENT_TYPES: SegmentDefinition[] = [
  {id:"user",label:"User",sample:"tim"},{id:"host",label:"Host",sample:"mac"},{id:"userHost",label:"User @ host",sample:"tim@mac"},{id:"directory",label:"Working directory",sample:"~/dev/termcraft"},
  {id:"gitBranch",label:"Git branch",sample:" main"},{id:"gitStatus",label:"Git status",sample:"±2 ↑1"},{id:"exitCode",label:"Exit code",sample:"✘1"},{id:"duration",label:"Execution time",sample:"2.4s"},
  {id:"time",label:"Current time",sample:"12:34"},{id:"venv",label:"Python venv",sample:"(venv)"},{id:"node",label:"Node version",sample:"node v22"},{id:"literal",label:"Literal string",sample:"❯"},{id:"newline",label:"Newline",sample:"\n"},
];
export interface PromptSegment { id: string; type: SegmentType; fg: number; bg: number; literal?: string; shorten?: number; tilde?: boolean; }
export interface PromptContext { dirty?: number; ahead?: number; behind?: number; exitCode?: number; cwd?: string; branch?: string; }
export interface StyledRun { text: string; fg?: number; bg?: number; }
export type SeparatorStyle = "powerline"|"powerline-thin"|"slant"|"round"|"space"|"custom";
export interface PromptOptions { separator?: SeparatorStyle; customSeparator?: string; }
const separators: Record<Exclude<SeparatorStyle,"custom">,string>={powerline:"","powerline-thin":"",slant:"",round:"",space:" "};
function textFor(s:PromptSegment,c:PromptContext):string { switch(s.type){case"user":return"tim";case"host":return"mac";case"userHost":return"tim@mac";case"directory":{let p=c.cwd??"~/dev/termcraft";if(s.tilde===false)p=p.replace(/^~/,"/Users/tim");const n=s.shorten??3,parts=p.split("/");return parts.length>n?"…/"+parts.slice(-n).join("/"):p;}case"gitBranch":return` ${c.branch??"main"}`;case"gitStatus":return c.dirty||c.ahead||c.behind?[c.dirty?`±${c.dirty}`:"",c.ahead?`↑${c.ahead}`:"",c.behind?`↓${c.behind}`:""].filter(Boolean).join(" "):"✓";case"exitCode":return(c.exitCode??0)===0?"✔":`✘${c.exitCode}`;case"duration":return"2.4s";case"time":return"12:34";case"venv":return"(venv)";case"node":return"node v22";case"literal":return s.literal??"❯";case"newline":return"\n";} }
export function renderPreview(segments:PromptSegment[],context:PromptContext={},opts:PromptOptions={}):StyledRun[]{const sep=opts.separator==="custom"?opts.customSeparator??"|":separators[opts.separator??"space"];const runs:StyledRun[]=[];segments.forEach((s,i)=>{const text=textFor(s,context);runs.push({text,fg:s.fg,bg:s.bg});if(s.type!=="newline"&&i<segments.length-1&&segments[i+1].type!=="newline")runs.push({text:sep,fg:s.bg,bg:segments[i+1].bg});});return runs;}
const esc=(fg:number,bg:number)=>`\\033[38;5;${fg};48;5;${bg}m`; const reset="\\033[0m";
const shellText=(s:PromptSegment)=>{const values:Record<SegmentType,string>={user:"\\u",host:"\\h",userHost:"\\u@\\h",directory:"\\w",gitBranch:"$(git branch --show-current 2>/dev/null)",gitStatus:"$(git diff --quiet || printf '±')",exitCode:"$?",duration:"2.4s",time:"\\t",venv:"${VIRTUAL_ENV:+($(basename \"$VIRTUAL_ENV\"))}",node:"$(node -v 2>/dev/null)",literal:s.literal??"❯",newline:"\\n"};return values[s.type];};
function exported(segments:PromptSegment[],opts:PromptOptions,wrap:(x:string)=>string):string {const sep=opts.separator==="custom"?opts.customSeparator??"|":separators[opts.separator??"space"];return segments.map((s,i)=>wrap(esc(s.fg,s.bg))+shellText(s)+wrap(reset)+(s.type!=="newline"&&i<segments.length-1?sep:"")).join("");}
export function toBash(segments:PromptSegment[],opts:PromptOptions={}):string{return`PS1='${exported(segments,opts,(x)=>`\\[${x}\\]`)} '`;}
export function toZsh(segments:PromptSegment[],opts:PromptOptions={}):string{return`PROMPT='${exported(segments,opts,(x)=>`%{${x}%}`)} '`;}
export function toFish(segments:PromptSegment[],opts:PromptOptions={}):string{const body=exported(segments,opts,(x)=>x).replace(/'/g,"\\'");return`function fish_prompt\n  printf '${body} '\nend`;}
export function toStarship(segments:PromptSegment[],opts:PromptOptions={}):string{const sep=opts.separator==="custom"?opts.customSeparator??"|":separators[opts.separator??"space"];const map:Partial<Record<SegmentType,string>>={user:"$username",host:"$hostname",directory:"$directory",gitBranch:"$git_branch",gitStatus:"$git_status",exitCode:"$status",duration:"$cmd_duration",time:"$time",venv:"$python",node:"$nodejs",newline:"$line_break"};const format=segments.map((s)=>map[s.type]??(s.type==="literal"?s.literal??"❯":"$username@$hostname")).join(sep);return`format = "${format}"\n\n[directory]\ntruncation_length = 3\n\n[git_status]\ndisabled = false\n\n[status]\ndisabled = false\n\n[time]\ndisabled = false`;}
