/**
 * CLI Spinner data
 *
 * Curated collection drawn from cli-spinners (sindresorhus) and
 * unicode-animations (gunnargray-dev), grouped by visual category.
 *
 * Each spinner: { name, interval (ms), frames: string[] }
 */

const SPINNERS = [
  // ── Braille Dots ──────────────────────────────────────────────
  {
    name: "dots",
    cat: "braille",
    interval: 80,
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
  },
  {
    name: "dots2",
    cat: "braille",
    interval: 80,
    frames: ["⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"],
  },
  {
    name: "dots3",
    cat: "braille",
    interval: 80,
    frames: ["⠋", "⠙", "⠚", "⠞", "⠖", "⠦", "⠴", "⠲", "⠳", "⠓"],
  },
  {
    name: "dots4",
    cat: "braille",
    interval: 80,
    frames: [
      "⠄",
      "⠆",
      "⠇",
      "⠋",
      "⠙",
      "⠸",
      "⠰",
      "⠠",
      "⠰",
      "⠸",
      "⠙",
      "⠋",
      "⠇",
      "⠆",
    ],
  },
  {
    name: "dots5",
    cat: "braille",
    interval: 80,
    frames: [
      "⠋",
      "⠙",
      "⠚",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠲",
      "⠴",
      "⠦",
      "⠖",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠓",
      "⠋",
    ],
  },
  {
    name: "dots6",
    cat: "braille",
    interval: 80,
    frames: [
      "⠁",
      "⠉",
      "⠙",
      "⠚",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠲",
      "⠴",
      "⠤",
      "⠄",
      "⠄",
      "⠤",
      "⠴",
      "⠲",
      "⠒",
      "⠂",
      "⠂",
      "⠒",
      "⠚",
      "⠙",
      "⠉",
      "⠁",
    ],
  },
  {
    name: "dots7",
    cat: "braille",
    interval: 80,
    frames: [
      "⠈",
      "⠉",
      "⠋",
      "⠓",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠖",
      "⠦",
      "⠤",
      "⠠",
      "⠠",
      "⠤",
      "⠦",
      "⠖",
      "⠒",
      "⠐",
      "⠐",
      "⠒",
      "⠓",
      "⠋",
      "⠉",
      "⠈",
    ],
  },
  {
    name: "dots9",
    cat: "braille",
    interval: 80,
    frames: ["⢹", "⢺", "⢼", "⣸", "⣇", "⡧", "⡗", "⡏"],
  },
  {
    name: "dots10",
    cat: "braille",
    interval: 80,
    frames: ["⢄", "⢂", "⢁", "⡁", "⡈", "⡐", "⡠"],
  },
  {
    name: "dots11",
    cat: "braille",
    interval: 100,
    frames: ["⠁", "⠂", "⠄", "⡀", "⢀", "⠠", "⠐", "⠈"],
  },
  {
    name: "dots13",
    cat: "braille",
    interval: 80,
    frames: ["⣼", "⣹", "⢻", "⠿", "⡟", "⣏", "⣧", "⣶"],
  },
  {
    name: "dots14",
    cat: "braille",
    interval: 80,
    frames: [
      "⠉⠉",
      "⠈⠙",
      "⠀⠹",
      "⠀⢸",
      "⠀⣰",
      "⢀⣠",
      "⣀⣀",
      "⣄⡀",
      "⣆⠀",
      "⡇⠀",
      "⠏⠀",
      "⠋⠁",
    ],
  },
  {
    name: "sand",
    cat: "braille",
    interval: 80,
    frames: [
      "⠁",
      "⠂",
      "⠄",
      "⡀",
      "⡈",
      "⡐",
      "⡠",
      "⣀",
      "⣁",
      "⣂",
      "⣄",
      "⣌",
      "⣔",
      "⣤",
      "⣥",
      "⣦",
      "⣮",
      "⣶",
      "⣷",
      "⣿",
      "⡿",
      "⠿",
      "⢟",
      "⠟",
      "⡛",
      "⠛",
      "⠫",
      "⢋",
      "⠋",
      "⠍",
      "⡉",
      "⠉",
      "⠑",
      "⠡",
      "⢁",
    ],
  },

  // ── Braille Multi-char ────────────────────────────────────────
  {
    name: "orbit",
    cat: "braille-multi",
    interval: 100,
    frames: ["⠃", "⠉", "⠘", "⠰", "⢠", "⣀", "⡄", "⠆"],
  },
  {
    name: "breathe",
    cat: "braille-multi",
    interval: 100,
    frames: [
      "⠀",
      "⠂",
      "⠌",
      "⡑",
      "⢕",
      "⢝",
      "⣫",
      "⣟",
      "⣿",
      "⣟",
      "⣫",
      "⢝",
      "⢕",
      "⡑",
      "⠌",
      "⠂",
      "⠀",
    ],
  },
  {
    name: "braillewave",
    cat: "braille-multi",
    interval: 100,
    frames: ["⠁⠂⠄⡀", "⠂⠄⡀⢀", "⠄⡀⢀⠠", "⡀⢀⠠⠐", "⢀⠠⠐⠈", "⠠⠐⠈⠁", "⠐⠈⠁⠂", "⠈⠁⠂⠄"],
  },
  {
    name: "dna",
    cat: "braille-multi",
    interval: 80,
    frames: [
      "⠋⠉⠙⠚",
      "⠉⠙⠚⠒",
      "⠙⠚⠒⠂",
      "⠚⠒⠂⠂",
      "⠒⠂⠂⠒",
      "⠂⠂⠒⠲",
      "⠂⠒⠲⠴",
      "⠒⠲⠴⠤",
      "⠲⠴⠤⠄",
      "⠴⠤⠄⠋",
      "⠤⠄⠋⠉",
      "⠄⠋⠉⠙",
    ],
  },
  {
    name: "scan",
    cat: "braille-multi",
    interval: 70,
    frames: [
      "⠀⠀⠀⠀",
      "⡇⠀⠀⠀",
      "⣿⠀⠀⠀",
      "⢸⡇⠀⠀",
      "⠀⣿⠀⠀",
      "⠀⢸⡇⠀",
      "⠀⠀⣿⠀",
      "⠀⠀⢸⡇",
      "⠀⠀⠀⣿",
      "⠀⠀⠀⢸",
    ],
  },
  {
    name: "rain",
    cat: "braille-multi",
    interval: 100,
    frames: ["⢁⠂⠔⠈", "⠂⠌⡠⠐", "⠄⡐⢀⠡", "⡈⠠⠀⢂", "⠐⢀⠁⠄", "⠠⠁⠊⡀"],
  },
  {
    name: "scanline",
    cat: "braille-multi",
    interval: 120,
    frames: ["⠉⠉⠉", "⠓⠓⠓", "⠦⠦⠦", "⣄⣄⣄", "⠦⠦⠦", "⠓⠓⠓"],
  },
  {
    name: "pulse",
    cat: "braille-multi",
    interval: 180,
    frames: ["⠀⠶⠀", "⠰⣿⠆", "⢾⣉⡷", "⣏⠀⣹", "⡁⠀⢈"],
  },
  {
    name: "snake",
    cat: "braille-multi",
    interval: 80,
    frames: [
      "⣁⡀",
      "⣉⠀",
      "⡉⠁",
      "⠉⠉",
      "⠈⠙",
      "⠀⠛",
      "⠐⠚",
      "⠒⠒",
      "⠖⠂",
      "⠶⠀",
      "⠦⠄",
      "⠤⠤",
      "⠠⢤",
      "⠀⣤",
      "⢀⣠",
      "⣀⣀",
    ],
  },
  {
    name: "sparkle",
    cat: "braille-multi",
    interval: 150,
    frames: ["⡡⠊⢔⠡", "⠊⡰⡡⡘", "⢔⢅⠈⢢", "⡁⢂⠆⡍", "⢔⠨⢑⢐", "⠨⡑⡠⠊"],
  },
  {
    name: "cascade",
    cat: "braille-multi",
    interval: 60,
    frames: [
      "⠀⠀⠀⠀",
      "⠁⠀⠀⠀",
      "⠋⠀⠀⠀",
      "⠞⠁⠀⠀",
      "⡴⠋⠀⠀",
      "⣠⠞⠁⠀",
      "⢀⡴⠋⠀",
      "⠀⣠⠞⠁",
      "⠀⢀⡴⠋",
      "⠀⠀⣠⠞",
      "⠀⠀⢀⡴",
      "⠀⠀⠀⣠",
      "⠀⠀⠀⢀",
      "⠀⠀⠀⠀",
    ],
  },
  {
    name: "columns",
    cat: "braille-multi",
    interval: 60,
    frames: [
      "⡀⠀⠀",
      "⡄⠀⠀",
      "⡆⠀⠀",
      "⡇⠀⠀",
      "⣇⠀⠀",
      "⣧⠀⠀",
      "⣷⠀⠀",
      "⣿⠀⠀",
      "⣿⡀⠀",
      "⣿⡄⠀",
      "⣿⡆⠀",
      "⣿⡇⠀",
      "⣿⣇⠀",
      "⣿⣧⠀",
      "⣿⣷⠀",
      "⣿⣿⠀",
      "⣿⣿⡀",
      "⣿⣿⡄",
      "⣿⣿⡆",
      "⣿⣿⡇",
      "⣿⣿⣇",
      "⣿⣿⣧",
      "⣿⣿⣷",
      "⣿⣿⣿",
      "⣿⣿⣿",
      "⠀⠀⠀",
    ],
  },
  {
    name: "waverows",
    cat: "braille-multi",
    interval: 90,
    frames: [
      "⠖⠉⠉⠑",
      "⡠⠖⠉⠉",
      "⣠⡠⠖⠉",
      "⣄⣠⡠⠖",
      "⠢⣄⣠⡠",
      "⠙⠢⣄⣠",
      "⠉⠙⠢⣄",
      "⠊⠉⠙⠢",
      "⠜⠊⠉⠙",
      "⡤⠜⠊⠉",
      "⣀⡤⠜⠊",
      "⢤⣀⡤⠜",
      "⠣⢤⣀⡤",
      "⠑⠣⢤⣀",
      "⠉⠑⠣⢤",
      "⠋⠉⠑⠣",
    ],
  },
  {
    name: "helix",
    cat: "braille-multi",
    interval: 80,
    frames: ["⢌⣉⢎⣉", "⣉⡱⣉⡱", "⣉⢎⣉⢎", "⡱⣉⡱⣉"],
  },
  {
    name: "fillsweep",
    cat: "braille-multi",
    interval: 100,
    frames: ["⣀⣀", "⣤⣤", "⣶⣶", "⣿⣿", "⣿⣿", "⣶⣶", "⣤⣤", "⣀⣀", "⠀⠀"],
  },
  {
    name: "diagswipe",
    cat: "braille-multi",
    interval: 60,
    frames: [
      "⠁⠀",
      "⠋⠀",
      "⠟⠁",
      "⡿⠋",
      "⣿⠟",
      "⣿⡿",
      "⣿⣿",
      "⣾⣿",
      "⣴⣿",
      "⣠⣾",
      "⢀⣴",
      "⠀⣠",
      "⠀⢀",
      "⠀⠀",
    ],
  },

  // ── Classic / Line ────────────────────────────────────────────
  {
    name: "line",
    cat: "classic",
    interval: 130,
    frames: ["-", "\\", "|", "/"],
  },
  {
    name: "line2",
    cat: "classic",
    interval: 100,
    frames: ["⠂", "-", "–", "—", "–", "-"],
  },
  {
    name: "pipe",
    cat: "classic",
    interval: 100,
    frames: ["┤", "┘", "┴", "└", "├", "┌", "┬", "┐"],
  },
  {
    name: "simpleDots",
    cat: "classic",
    interval: 400,
    frames: [".  ", ".. ", "...", "   "],
  },
  {
    name: "simpleDotsScrolling",
    cat: "classic",
    interval: 200,
    frames: [".  ", ".. ", "...", " ..", "  .", "   "],
  },
  {
    name: "star",
    cat: "classic",
    interval: 70,
    frames: ["✶", "✸", "✹", "✺", "✹", "✷"],
  },
  { name: "star2", cat: "classic", interval: 80, frames: ["+", "x", "*"] },
  {
    name: "flip",
    cat: "classic",
    interval: 70,
    frames: ["_", "_", "_", "-", "`", "`", "'", "´", "-", "_", "_", "_"],
  },
  {
    name: "balloon",
    cat: "classic",
    interval: 140,
    frames: [" ", ".", "o", "O", "@", "*", " "],
  },
  {
    name: "balloon2",
    cat: "classic",
    interval: 120,
    frames: [".", "o", "O", "°", "O", "o", "."],
  },
  { name: "noise", cat: "classic", interval: 100, frames: ["▓", "▒", "░"] },
  {
    name: "bounce",
    cat: "classic",
    interval: 120,
    frames: ["⠁", "⠂", "⠄", "⠂"],
  },
  {
    name: "binary",
    cat: "classic",
    interval: 80,
    frames: [
      "010010",
      "001100",
      "100101",
      "111010",
      "111101",
      "010111",
      "101011",
      "111000",
      "110011",
      "110101",
    ],
  },
  { name: "layer", cat: "classic", interval: 150, frames: ["-", "=", "≡"] },
  {
    name: "betaWave",
    cat: "classic",
    interval: 80,
    frames: [
      "ρββββββ",
      "βρβββββ",
      "ββρββββ",
      "βββρβββ",
      "ββββρββ",
      "βββββρβ",
      "ββββββρ",
    ],
  },

  // ── Geometric ─────────────────────────────────────────────────
  {
    name: "hamburger",
    cat: "geometric",
    interval: 100,
    frames: ["☱", "☲", "☴"],
  },
  {
    name: "growVertical",
    cat: "geometric",
    interval: 120,
    frames: ["▁", "▃", "▄", "▅", "▆", "▇", "▆", "▅", "▄", "▃"],
  },
  {
    name: "growHorizontal",
    cat: "geometric",
    interval: 120,
    frames: ["▏", "▎", "▍", "▌", "▋", "▊", "▉", "▊", "▋", "▌", "▍", "▎"],
  },
  {
    name: "boxBounce",
    cat: "geometric",
    interval: 120,
    frames: ["▖", "▘", "▝", "▗"],
  },
  {
    name: "boxBounce2",
    cat: "geometric",
    interval: 100,
    frames: ["▌", "▀", "▐", "▄"],
  },
  {
    name: "triangle",
    cat: "geometric",
    interval: 50,
    frames: ["◢", "◣", "◤", "◥"],
  },
  {
    name: "arc",
    cat: "geometric",
    interval: 100,
    frames: ["◜", "◠", "◝", "◞", "◡", "◟"],
  },
  { name: "circle", cat: "geometric", interval: 120, frames: ["◡", "⊙", "◠"] },
  {
    name: "squareCorners",
    cat: "geometric",
    interval: 180,
    frames: ["◰", "◳", "◲", "◱"],
  },
  {
    name: "circleQuarters",
    cat: "geometric",
    interval: 120,
    frames: ["◴", "◷", "◶", "◵"],
  },
  {
    name: "circleHalves",
    cat: "geometric",
    interval: 50,
    frames: ["◐", "◓", "◑", "◒"],
  },
  { name: "squish", cat: "geometric", interval: 100, frames: ["╫", "╪"] },
  {
    name: "dqpb",
    cat: "geometric",
    interval: 100,
    frames: ["d", "q", "p", "b"],
  },

  // ── Toggle ────────────────────────────────────────────────────
  { name: "toggle", cat: "toggle", interval: 250, frames: ["⊶", "⊷"] },
  { name: "toggle2", cat: "toggle", interval: 80, frames: ["▫", "▪"] },
  { name: "toggle3", cat: "toggle", interval: 120, frames: ["□", "■"] },
  {
    name: "toggle4",
    cat: "toggle",
    interval: 100,
    frames: ["■", "□", "▪", "▫"],
  },
  { name: "toggle5", cat: "toggle", interval: 100, frames: ["▮", "▯"] },
  { name: "toggle6", cat: "toggle", interval: 300, frames: ["ဝ", "၀"] },
  { name: "toggle7", cat: "toggle", interval: 80, frames: ["⦾", "⦿"] },
  { name: "toggle8", cat: "toggle", interval: 100, frames: ["◍", "◌"] },
  { name: "toggle9", cat: "toggle", interval: 100, frames: ["◉", "◎"] },
  {
    name: "toggle10",
    cat: "toggle",
    interval: 100,
    frames: ["㊂", "㊀", "㊁"],
  },
  { name: "toggle11", cat: "toggle", interval: 50, frames: ["⧇", "⧆"] },
  { name: "toggle12", cat: "toggle", interval: 120, frames: ["☗", "☖"] },
  { name: "toggle13", cat: "toggle", interval: 80, frames: ["=", "*", "-"] },

  // ── Arrows ────────────────────────────────────────────────────
  {
    name: "arrow",
    cat: "arrow",
    interval: 100,
    frames: ["←", "↖", "↑", "↗", "→", "↘", "↓", "↙"],
  },
  {
    name: "arrow3",
    cat: "arrow",
    interval: 120,
    frames: ["▹▹▹▹▹", "▸▹▹▹▹", "▹▸▹▹▹", "▹▹▸▹▹", "▹▹▹▸▹", "▹▹▹▹▸"],
  },
  {
    name: "bouncingBar",
    cat: "arrow",
    interval: 80,
    frames: [
      "[    ]",
      "[=   ]",
      "[==  ]",
      "[=== ]",
      "[====]",
      "[ ===]",
      "[  ==]",
      "[   =]",
      "[    ]",
      "[   =]",
      "[  ==]",
      "[ ===]",
      "[====]",
      "[=== ]",
      "[==  ]",
      "[=   ]",
    ],
  },
  {
    name: "bouncingBall",
    cat: "arrow",
    interval: 80,
    frames: [
      "( ●    )",
      "(  ●   )",
      "(   ●  )",
      "(    ● )",
      "(     ●)",
      "(    ● )",
      "(   ●  )",
      "(  ●   )",
      "( ●    )",
      "(●     )",
    ],
  },

  // ── Progress / Bar ────────────────────────────────────────────
  {
    name: "aesthetic",
    cat: "progress",
    interval: 80,
    frames: [
      "▰▱▱▱▱▱▱",
      "▰▰▱▱▱▱▱",
      "▰▰▰▱▱▱▱",
      "▰▰▰▰▱▱▱",
      "▰▰▰▰▰▱▱",
      "▰▰▰▰▰▰▱",
      "▰▰▰▰▰▰▰",
      "▰▱▱▱▱▱▱",
    ],
  },
  {
    name: "point",
    cat: "progress",
    interval: 125,
    frames: ["∙∙∙", "●∙∙", "∙●∙", "∙∙●", "∙∙∙"],
  },
  {
    name: "dotsCircle",
    cat: "progress",
    interval: 80,
    frames: ["⢎ ", "⠎⠁", "⠊⠑", "⠈⠱", " ⡱", "⢀⡰", "⢄⡠", "⢆⡀"],
  },

  // ── Emoji ─────────────────────────────────────────────────────
  {
    name: "clock",
    cat: "emoji",
    interval: 100,
    frames: [
      "🕛",
      "🕐",
      "🕑",
      "🕒",
      "🕓",
      "🕔",
      "🕕",
      "🕖",
      "🕗",
      "🕘",
      "🕙",
      "🕚",
    ],
  },
  { name: "earth", cat: "emoji", interval: 180, frames: ["🌍", "🌎", "🌏"] },
  {
    name: "moon",
    cat: "emoji",
    interval: 80,
    frames: ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘"],
  },
  {
    name: "hearts",
    cat: "emoji",
    interval: 100,
    frames: ["💛", "💙", "💜", "💚", "💗"],
  },
  {
    name: "fingerDance",
    cat: "emoji",
    interval: 160,
    frames: ["🤘", "🤟", "🖖", "✋", "🤚", "👆"],
  },
  {
    name: "speaker",
    cat: "emoji",
    interval: 160,
    frames: ["🔈", "🔉", "🔊", "🔉"],
  },
  {
    name: "weather",
    cat: "emoji",
    interval: 100,
    frames: [
      "☀️",
      "☀️",
      "☀️",
      "🌤",
      "⛅️",
      "🌥",
      "☁️",
      "🌧",
      "🌨",
      "🌧",
      "🌥",
      "⛅️",
      "🌤",
      "☀️",
      "☀️",
    ],
  },
  { name: "christmas", cat: "emoji", interval: 400, frames: ["🌲", "🎄"] },
  {
    name: "mindblown",
    cat: "emoji",
    interval: 160,
    frames: [
      "😐",
      "😐",
      "😮",
      "😮",
      "😦",
      "😦",
      "😧",
      "😧",
      "🤯",
      "💥",
      "✨",
      "  ",
      "  ",
      "  ",
    ],
  },
  {
    name: "fistBump",
    cat: "emoji",
    interval: 80,
    frames: [
      "🤜\u3000\u3000\u3000\u3000🤛",
      "🤜\u3000\u3000\u3000\u3000🤛",
      "🤜\u3000\u3000\u3000\u3000🤛",
      "\u3000🤜\u3000\u3000🤛\u3000",
      "\u3000\u3000🤜🤛\u3000\u3000",
      "\u3000🤜✨🤛\u3000\u3000",
      "🤜\u3000✨\u3000🤛\u3000",
    ],
  },
];

/** Category display names */
const CATEGORIES = {
  braille: "Braille Dots",
  "braille-multi": "Braille Patterns",
  classic: "Classic",
  geometric: "Geometric",
  toggle: "Toggle",
  arrow: "Arrows & Bars",
  progress: "Progress",
  emoji: "Emoji",
};

/** Ordered category keys */
const CATEGORY_ORDER = Object.keys(CATEGORIES);

export function getSpinners() {
  return SPINNERS;
}

export function getCategories() {
  return CATEGORIES;
}

export function getCategoryOrder() {
  return CATEGORY_ORDER;
}

export function getSpinnersByCategory() {
  const grouped = {};
  for (const key of CATEGORY_ORDER) {
    grouped[key] = SPINNERS.filter((s) => s.cat === key);
  }
  return grouped;
}

export function getSpinnerByName(name) {
  return SPINNERS.find((s) => s.name === name);
}
